language:
  - cpp
  - python

python: 3.7

cache:
  apt: true

addons:
  apt:
    sources:
      - sourceline: 'ppa:graphics-drivers/ppa'
    packages:
      - cmake
      - g++-6
      - clang-4.0
      - libvulkan-dev
      - libegl1-mesa-dev

matrix:
  include:
    - os: windows
      before_install:
        - choco install python3
        - export PATH="/c/Python39:/c/Python39/Scripts:$PATH"
        - wget http://anki3d.org/VulkanSDKLib.zip
        - unzip VulkanSDKLib.zip -d vulkansdk
        - export VULKAN_SDK=$TRAVIS_BUILD_DIR/vulkansdk
      env:
        - GENERATOR="Visual Studio 15 2017 Win64" BUILD_TYPE=Debug EXTRA_CHECKS=ON TRACE=ON TOOLS=ON TESTS=ON
        - GENERATOR="Visual Studio 15 2017 Win64" BUILD_TYPE=Release EXTRA_CHECKS=OFF TRACE=OFF TOOLS=ON TESTS=ON
    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - GENERATOR="Unix Makefiles" BUILD_TYPE=Debug EXTRA_CHECKS=ON TRACE=ON TOOLS=ON TESTS=ON
        - GENERATOR="Unix Makefiles" BUILD_TYPE=Release EXTRA_CHECKS=OFF TRACE=OFF TOOLS=ON TESTS=ON
    - os: linux
      dist: bionic
      compiler: clang
      env:
        - GENERATOR="Unix Makefiles" BUILD_TYPE=Debug EXTRA_CHECKS=ON TRACE=ON TOOLS=ON TESTS=ON
        - GENERATOR="Unix Makefiles" BUILD_TYPE=Release EXTRA_CHECKS=OFF TRACE=OFF TOOLS=ON TESTS=ON

script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then PYTHON3=$(which python); fi
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then PYTHON3=$(which python3); fi
  - $CC --version
  - $CXX --version
  - echo "VULKAN_SDK ENV" $VULKAN_SDK
  - mkdir build
  - cd build
  - cmake .. -G "${GENERATOR}" -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DANKI_EXTRA_CHECKS=${EXTRA_CHECKS} -DANKI_BUILD_TOOLS=${TOOLS} -DANKI_BUILD_TESTS=${TESTS} -DANKI_TRACE=${TRACE} -DPYTHON_EXECUTABLE:FILEPATH="${PYTHON3}"
  - cmake --build . --config ${BUILD_TYPE}
