name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    name: "Build Android"
    runs-on: ubuntu-latest
    container: ghcr.io/khronosgroup/vulkan-samples

    steps:
    - name: Install dependencies
      run: |
        add-apt-repository -y ppa:ubuntu-toolchain-r/test
        apt-get update
        apt update
        apt install ninja-build gcc-11 g++-11

    - name: Clone
      uses: actions/checkout@v3

    - name: Configure CMake for Linux
      run: cmake -B ${{github.workspace}}/build -DANKI_BUILD_TESTS=OFF -DCMAKE_BUILD_TYPE=Release -DANKI_EXTRA_CHECKS=OFF -DCMAKE_C_COMPILER=gcc-11 -DCMAKE_CXX_COMPILER=g++-11

    - name: Build Linux ShaderCompiler
      run: cmake --build ${{github.workspace}}/build --config Release --target ShaderCompiler

    - name: Generate project
      run: ./Samples/Sponza/GenerateAndroidProject.sh ${{github.workspace}}/build/Bin/ShaderCompiler

    - name: local.properties
      run: |
        echo "sdk.dir=/usr/local/android-sdk" > AndroidProject_Sponza/local.properties
        echo "ndk.dir=/usr/local/android-ndk" >> AndroidProject_Sponza/local.properties

    - name: Build Android
      working-directory: AndroidProject_Sponza
      run: ./gradlew build
